name: Entrega continua

on:
  workflow_call:
jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo su -
          yum update -y
          yum install -y httpd
          systemctl status httpd
          mkdir temp
          cd temp
          wget https://www.free-css.com/assets/files/free-css-templates/download/page269/complex.zip
          unzip complex.zip
          cd complex
          mv * /var/www/html/
          systemctl enable httpd
          systemctl start httpd
